<package format="3">
  <name>mujoco_ros_utils</name>
  <version>0.1.0</version>
  <description>
    ROS-based MuJoCo utilities
  </description>
  <maintainer email="m-murooka@aist.go.jp">Masaki Murooka</maintainer>
  <license>BSD-2-Clause</license>

  <url>http://ros.org/wiki/mujoco_ros_utils</url>
  <author>Masaki Murooka</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rosidl_default_generators</build_depend>

  <depend>ament_index_cpp</depend>
  <depend>builtin_interfaces</depend>
  <depend>controller_manager</depend>
  <depend>control_toolbox</depend>
  <depend>cv_bridge</depend>
  <depend>geometry_msgs</depend>
  <depend>hardware_interface</depend>
  <depend>image_geometry</depend>
  <depend>image_transport</depend>
  <depend>joint_limits</depend>
  <depend>libglfw3-dev</depend>
  <depend>libhdf5-dev</depend>
  <depend>libx11-dev</depend>
  <depend>opengl</depend>
  <depend>pluginlib</depend>
  <depend>pkg-config</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>
  <depend>sensor_msgs</depend>
  <depend>sdl2</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>trajectory_msgs</depend>
  <depend>urdf</depend>
  <depend>visualization_msgs</depend>

  <exec_depend>image_transport_plugins</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>rclpy</test_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <doc_depend>doxygen</doc_depend>
  <doc_depend>graphviz</doc_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
